name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build And Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Get Package Version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> "$GITHUB_ENV"

      - name: Install Dependencies
        run: npm ci

      - name: Build Code
        run: npm run build

      - name: Publish Package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./publish/CURRENT_CHANGELOG.md
          prerelease: false
          draft: false
          tag_name: ${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
